name: Docker

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  compose-build:
    name: Docker Compose Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build